# Generated by Django 5.0.4 on 2026-08-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The website this account administers.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_accounts",
                to="saas.tenant",
            ),
        ),
    ]
