# Generated by Django 5.0.4 on 2026-08-22 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_note",
            field=models.TextField(
                blank=True,
                help_text="Extra line shown in the footer, above the copyright.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_header_search",
            field=models.BooleanField(
                default=True, verbose_name="Show the search box in the masthead"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_ticker",
            field=models.BooleanField(
                default=True, verbose_name='Show the scrolling "what\'s new" ticker'
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_top_strip",
            field=models.BooleanField(
                default=True, verbose_name="Show the authority strip above the masthead"
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("image", models.ImageField(blank=True, upload_to="banners/")),
                ("link_url", models.CharField(blank=True, max_length=300)),
                (
                    "link_text",
                    models.CharField(blank=True, default="Read more", max_length=60),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_hero", "Home page — below the hero"),
                            ("home_strip", "Home page — full-width strip"),
                            ("sitewide_top", "Site-wide — under the navigation"),
                            ("inner_page", "Inner pages — sidebar"),
                        ],
                        default="home_strip",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banners_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["placement", "order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "payload",
                    models.TextField(
                        help_text="The URL or text the code points to, e.g. https://example.org/membership/"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("footer", "Footer"),
                            ("contact", "Contact page"),
                            ("home_sidebar", "Home page — sidebar"),
                            ("membership", "Membership page"),
                            ("none", "Not displayed (link only)"),
                        ],
                        default="footer",
                        max_length=20,
                    ),
                ),
                (
                    "error_correction",
                    models.CharField(
                        choices=[
                            ("L", "L — recovers 7%"),
                            ("M", "M — recovers 15%"),
                            ("Q", "Q — recovers 25%"),
                            ("H", "H — recovers 30% (best for printed codes)"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional: upload a ready-made code to use instead of the generated one.",
                        upload_to="qr/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "scans_hint",
                    models.CharField(
                        blank=True,
                        help_text="Short instruction shown under the code.",
                        max_length=120,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_codes_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QR code",
                "ordering": ["order", "label"],
            },
        ),
    ]
