# Generated by Django 5.0.4 on 2026-08-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_sitesettings_footer_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="emblem",
            field=models.ImageField(
                blank=True,
                help_text="Round seal or crest. Used when no logo is uploaded; a built-in mark is drawn if neither is set.",
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Shown in the masthead, the footer and the admin panel. Takes precedence over the emblem.",
                upload_to="site/",
            ),
        ),
    ]
