# Generated by Django 5.0.4 on 2026-08-22 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Signed in"),
                            ("login_failed", "Failed sign-in"),
                            ("logout", "Signed out"),
                            ("password_changed", "Changed password"),
                            ("password_reset", "Password reset to default"),
                            ("admin_created", "Created an administrator"),
                            ("admin_updated", "Updated an administrator"),
                            ("admin_suspended", "Suspended an administrator"),
                            ("admin_restored", "Restored an administrator"),
                            ("elevation_granted", "Elevated to Super Admin"),
                            ("elevation_denied", "Elevation refused"),
                            ("elevation_revoked", "Elevation ended"),
                            ("secret_rotated", "Rotated the elevation secret"),
                            ("content_updated", "Updated content"),
                            ("content_created", "Created content"),
                            ("content_deleted", "Deleted content"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("was_elevated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PanelSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret_hash", models.CharField(max_length=256)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Allow Admins to elevate with the secret",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="panel_secrets_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Elevation secret",
                "verbose_name_plural": "Elevation secret",
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("super_admin", "Super Admin"), ("admin", "Admin")],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True,
                        help_text="While set, the account can do nothing but change its password.",
                    ),
                ),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Unset to suspend the account without deleting it.",
                    ),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "failed_elevation_attempts",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("elevation_locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff account",
                "ordering": ["role", "user__username"],
            },
        ),
    ]
